version: "3.8"
services:
  java:
    image: tempchloer/final-sprint-frontend
    build: ./frontend
    ports:
      - target: 8000
        published: 8000
  react:
    image: tempchloer/final-sprint-backend
    build:
      context: ./backend
    ports:
      - target: 80
        published: 80
