version: "3.8"
services:
  java:
    image: scottobrien1/final-sprint-frontend
    build: ./frontend
    ports:
      - target: 8080
        published: 8080
  react:
    image: scottobrien1/final-sprint-backend
    build:
      context: ./backend
    ports:
      - target: 80
        published: 80